const { chromium } = require('/opt/node22/lib/node_modules/playwright');
(async () => {
  const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1440,height:900}}); const erros = []; p.on('pageerror', e => erros.push(e.message));
  const ok = (c, m) => console.log((c ? 'OK   ' : 'FALHA') + ' ' + m);
  await p.route(/fonts\./, r => r.abort());
  await p.goto('file://' + process.cwd() + '/wrap.html'); await p.evaluate(() => localStorage.clear()); await p.reload(); await p.waitForTimeout(300);
  await p.click('[data-tela=operacoes]'); await p.waitForTimeout(300);
  const cores = await p.evaluate(() => { const c = s => { const e = document.querySelector(s); return e && getComputedStyle(e).backgroundColor; }; return {proj:c('.no-arv[data-no^="project:"]'), app:c('.no-arv[data-no^="app:"]:not(.escolhido)'), prod:c('.no-arv[data-no^="product:"]:not(.escolhido)')}; });
  ok(cores.app.includes('255, 0, 0'), 'aplicação com camada vermelha leve ' + cores.app); ok(!cores.prod.includes('255, 0, 0'), 'produto sem vermelho ' + cores.prod); ok(cores.proj !== 'rgba(0, 0, 0, 0)', 'projeto escuro ' + cores.proj);
  await p.locator('.ops-arvore').screenshot({path:'../arvore.png'});
  await p.click('[data-tela=custos]'); await p.waitForTimeout(200); await p.click('[data-ct-aba=dominios]'); await p.waitForTimeout(300);
  ok(await p.isVisible('text=it-ia.tec.br'), 'aba Domínios mostra it-ia.tec.br');
  await p.click('[data-dm-abrir]'); await p.waitForTimeout(200);
  ok((await p.locator('.dm-det tbody tr').count()) === 9, '9 registros no detalhe');
  ok(await p.isVisible('text=ciclodev.it-ia.tec.br'), 'subdomínio ciclodev aparece com o endereço completo');
  await p.screenshot({path:'../dominios.png', fullPage:false});
  await p.click('[data-dm=novo]'); await p.fill('#dm-n', 'exemplo com espaço'); await p.click('dialog [data-b="1"]'); await p.waitForTimeout(100);
  ok(await p.isVisible('dialog'), 'nome inválido não salva');
  await p.fill('#dm-n', 'https://Blancoelisboa.com.br/'); await p.fill('#dm-v', '2026-10-20'); await p.click('dialog [data-b="1"]'); await p.waitForTimeout(300);
  ok(await p.isVisible('text=blancoelisboa.com.br'), 'domínio novo salvo (endereço limpo e em minúsculas)');
  ok(await p.isVisible('text=Vence em 22 dias'), 'situação calcula dias para vencer');
  await p.reload(); await p.waitForTimeout(300); await p.click('[data-tela=custos]'); await p.click('[data-ct-aba=dominios]'); await p.waitForTimeout(300);
  ok(await p.isVisible('text=blancoelisboa.com.br'), 'continua salvo depois de recarregar');
  const lin = p.locator('tr', {hasText:'blancoelisboa.com.br'}); await lin.locator('[data-dm-abrir]').click(); await p.click('[data-dm-novo-reg]');
  await p.fill('#dr-n', 'www.blancoelisboa.com.br'); await p.fill('#dr-a', 'cname.vercel-dns.com'); await p.click('dialog [data-b="1"]'); await p.waitForTimeout(300);
  ok(await p.isVisible('text=www.blancoelisboa.com.br'), 'registro novo salvo, mesmo digitando o endereço inteiro');
  await p.locator('tr', {hasText:'blancoelisboa.com.br'}).first().locator('[data-dm-excluir]').click(); await p.click('dialog [data-b="1"]'); await p.waitForTimeout(300);
  ok(!(await p.isVisible('text=blancoelisboa.com.br')), 'excluir domínio funciona');
  const larg = await p.evaluate(() => [document.documentElement.scrollWidth, innerWidth]);
  await p.setViewportSize({width:390, height:800}); await p.waitForTimeout(200); const m = await p.evaluate(() => [document.documentElement.scrollWidth, innerWidth]); ok(m[0] <= m[1], 'celular sem rolagem para o lado ' + m);
  console.log('ERROS', erros); await b.close();
})();
