# Explicação simples de cada "i" do sistema.
# Chave: o texto original do "i". Valor: o texto que aparece na caixinha.
# Regra: termo (tradução), dois pontos, o que é e para que serve, em linguagem de quem não é da área.
EXPL = {
 "APIs (canais de conversa entre sistemas)": "APIs (canais de conversa entre sistemas): as portas por onde um sistema pede ou manda dados para outro, sem ninguém digitar nada. Aqui fica a lista delas.",
 "Active (ativo)": "Active (ativo): o projeto está andando normalmente, com gente trabalhando nele.",
 "Agent Core (o banco de memória técnica dos agentes)": "Agent Core (memória técnica dos agentes): o banco onde os agentes de IA guardam o que aprenderam sobre os sistemas, para não perguntar de novo o que já foi respondido.",
 "Application (aplicação)": "Application (aplicação): um sistema específico que é entregue ao cliente, como um app de celular ou um site. Fica dentro de um produto ou direto no projeto.",
 "Approval (aprovação)": "Approval (aprovação): a etapa em que o responsável confere a entrega e diz sim, pode ir para o ar.",
 "Archived (arquivado)": "Archived (arquivado): o projeto saiu da lista do dia a dia, mas continua guardado com todo o histórico. Nada é apagado.",
 "Assignee (responsável, quem vai fazer)": "Assignee (responsável): a pessoa que vai fazer este item. É ela que aparece no cartão e recebe a carga de horas.",
 "Audit log (registro de quem fez o quê)": "Audit log (registro de auditoria): um diário automático que anota quem mudou o quê e quando. Serve para descobrir a origem de qualquer mudança.",
 "Backlog (na fila, ainda não planejado)": "Backlog (fila de espera): itens que já foram anotados, mas ainda não têm data para começar. É a lista do que vem depois.",
 "Baseline requirements (requisitos mínimos obrigatórios em todo sistema desenvolvido)": "Baseline requirements (requisitos mínimos): a lista do que todo sistema da IT.IA precisa ter, sempre, como login seguro, cópia de segurança e registro de erros.",
 "Baseline requirements (requisitos mínimos obrigatórios em todo sistema)": "Baseline requirements (requisitos mínimos): a lista do que todo sistema da IT.IA precisa ter, sempre, como login seguro, cópia de segurança e registro de erros.",
 "Baseline requirements (requisitos mínimos obrigatórios)": "Baseline requirements (requisitos mínimos): a lista do que todo sistema deste serviço precisa ter, sempre, antes de ser entregue.",
 "Blocked (bloqueado, esperando algo)": "Blocked (bloqueado): o item parou porque depende de alguma coisa, como uma resposta do cliente ou outra tarefa. Fica em vermelho para chamar atenção.",
 "Brownfield (projeto que já existe e é trazido em andamento)": "Brownfield (projeto já existente): um sistema que já estava funcionando e chega à IT.IA para continuar. Primeiro se levanta o que existe, depois se mexe.",
 "Bug (defeito)": "Bug (defeito): algo que devia funcionar e não funciona. Entra como item para ser corrigido.",
 "Build (construção)": "Build (construção): a etapa em que o sistema é programado de fato, seguindo o que foi desenhado e planejado.",
 "Business rules (regras de negócio)": "Business rules (regras de negócio): as regras da empresa que o sistema precisa respeitar, como 'nota só sai depois do pagamento'.",
 "Checklist (lista de conferência)": "Checklist (lista de conferência): pequenos passos dentro do item. Cada um é marcado quando fica pronto, e a barra mostra quanto falta.",
 "Client (cliente)": "Client (cliente): a empresa que contrata a IT.IA. Tudo o que é feito para ela fica guardado abaixo dela.",
 "Clients (clientes)": "Clients (clientes): o cadastro das empresas que contratam a IT.IA, inclusive a holding Blanco & Lisboa e as empresas do grupo.",
 "Comments (comentários)": "Comments (comentários): a conversa sobre o item, com data e autor. Fica tudo registrado junto da tarefa.",
 "Custom fields (campos personalizados)": "Custom fields (campos personalizados): informações extras que você cria para este projeto, além das que o sistema já traz.",
 "Data model (modelo de dados: a lista das tabelas do banco e o que cada uma guarda)": "Data model (modelo de dados): a planta do banco. Mostra cada tabela, o que ela guarda e como uma se liga à outra.",
 "Database (banco de dados)": "Database (banco de dados): onde o sistema guarda todas as informações de forma permanente, como clientes, tarefas e valores.",
 "Decisions (decisões tomadas)": "Decisions (decisões): o registro das escolhas importantes do projeto e do motivo de cada uma, para ninguém refazer a discussão depois.",
 "Deixe o limite em zero se este custo não tem limite de uso": "Limite de uso: se o plano deste serviço não tem teto de consumo, deixe zero e o sistema não vai avisar sobre limite.",
 "Design (desenho da solução)": "Design (desenho da solução): a etapa em que se decide como o sistema vai ser, telas e funcionamento, antes de programar.",
 "Discovery (levantamento do que existe)": "Discovery (levantamento): a etapa de entender o problema, o que já existe e o que o cliente realmente precisa.",
 "Done (concluído)": "Done (concluído): o item foi feito e conferido. Conta no progresso.",
 "Drag to reschedule (arrastar para mudar a data)": "Drag to reschedule (arrastar para remarcar): segure um item no calendário e solte em outro dia para mudar a data dele.",
 "Drill-down (ir descendo nos detalhes, do macro ao micro)": "Drill-down (descer no detalhe): clicar numa linha para ver o que existe dentro dela, do geral para o específico. O Voltar sobe um nível.",
 "Due date (prazo)": "Due date (prazo): a data limite para o item estar pronto. Depois dela, o item aparece como atrasado.",
 "Environments (ambientes onde o sistema roda)": "Environments (ambientes): as cópias do sistema, como a de testes e a de uso real. Mexe-se primeiro no teste para não quebrar a real.",
 "Epic (grande entrega)": "Epic (grande entrega): um bloco grande de trabalho que é dividido em várias stories e tarefas, como 'Área do cliente'.",
 "Estimate (estimativa de esforço, em horas)": "Estimate (estimativa): quantas horas se acha que o item vai levar. Serve para planejar a semana e calcular o custo.",
 "Estimativa média no Lucro Real": "Lucro Real: regime de impostos calculado sobre o lucro de verdade. O valor aqui é uma média para estimar o preço.",
 "Evidence (prova: o que mostra que o item foi cumprido de verdade)": "Evidence (prova): o que mostra que algo foi feito de verdade, como um print, um link ou um arquivo. Não vale só dizer que fez.",
 "Exchange rate (câmbio do dia)": "Exchange rate (câmbio): quanto vale um dólar em reais hoje. Usado para converter custos cobrados em dólar.",
 "Fixed price (preço fechado pelo escopo)": "Fixed price (preço fechado): o cliente paga um valor combinado antes para uma entrega definida, não importa quantas horas leve.",
 "Folga sobre o rateio da operação interna": "Folga do rateio: uma margem extra sobre os custos da operação, para cobrir gastos que aparecem sem aviso.",
 "Fora do Simples": "Fora do Simples: este encargo só é cobrado de empresas que não estão no Simples Nacional.",
 "GRANT (a liberação da operação: ler, gravar, apagar)": "GRANT (permissão): a autorização no banco para ler, gravar ou apagar numa tabela. Sem ela a tela quebra, mesmo com a regra de quem vê cada linha.",
 "Greenfield (projeto que começa do zero)": "Greenfield (projeto do zero): um sistema novo, sem nada anterior. Dá para fazer tudo do jeito certo desde o começo.",
 "Handoff rules (quando o agente passa a conversa para uma pessoa)": "Handoff rules (regras de passagem): em que situação o agente de IA para de responder e chama uma pessoa, como reclamação ou pedido de preço.",
 "High (alta)": "High (prioridade alta): importante, deve ser feito logo depois das urgências.",
 "Highest (urgentíssima)": "Highest (urgentíssima): passa na frente de tudo, normalmente porque algo parou de funcionar.",
 "Horas que ainda faltam nas tarefas abertas vezes o custo hora do time, com contingência": "Equipe para terminar: as horas que faltam nas tarefas abertas multiplicadas pelo custo de uma hora do time, com uma reserva para imprevistos.",
 "Hour bank (banco de horas pré-pago, com desconto)": "Hour bank (banco de horas): o cliente compra um pacote de horas adiantado, com desconto, e vai usando conforme precisa.",
 "ID (o código interno do banco, que nunca muda)": "ID (código interno): um número único que o banco dá a cada registro. O nome pode mudar, o ID nunca, e é por ele que as coisas se ligam.",
 "ISS, PIS, COFINS, IRPJ e CSLL somados": "Impostos sobre a nota: a soma dos impostos cobrados sobre o que se fatura. Entra no cálculo do preço.",
 "Idempotent (processar a mesma coisa duas vezes dá o mesmo resultado de uma vez)": "Idempotente: se a mesma ordem chegar duas vezes, o resultado é igual a uma vez só. Evita, por exemplo, cobrar o cliente em dobro.",
 "Implementation fee (taxa de implantação, paga uma vez)": "Implementation fee (taxa de implantação): um valor único cobrado para colocar o sistema para funcionar no cliente.",
 "In Progress (em andamento)": "In Progress (em andamento): alguém está trabalhando neste item agora.",
 "In Review (em revisão)": "In Review (em revisão): o item foi feito e está sendo conferido antes de ser dado como concluído.",
 "Inherits (herda: já nasce com o que o projeto definiu)": "Inherits (herda): este nível já vem com as informações do nível de cima, sem precisar preencher de novo. Só muda o que for diferente.",
 "Instructions ou System prompt (as instruções fixas de como o agente se comporta)": "Instructions (instruções do agente): o texto fixo que diz ao agente de IA quem ele é, como falar e o que pode ou não fazer.",
 "Intake (entrada e triagem do pedido)": "Intake (entrada): a etapa em que o pedido chega, é entendido e se decide se vira projeto.",
 "Integrations (ligações com outros sistemas)": "Integrations (integrações): os outros sistemas com que este conversa, como WhatsApp, banco ou emissor de nota.",
 "Issues (itens): todas as tarefas, stories, epics e bugs deste nível": "Issues (itens): tudo o que tem para fazer neste nível, sejam tarefas, funcionalidades, grandes entregas ou defeitos.",
 "Kickoff checklist (o que precisa existir antes de começar)": "Kickoff checklist (lista para começar): o que precisa estar pronto antes do primeiro dia de trabalho, como acessos e contrato.",
 "Knowledge sources (fontes de conhecimento: de onde o agente tira as respostas, via RAG)": "Knowledge sources (fontes de conhecimento): os documentos que o agente de IA consulta antes de responder, para falar só o que é verdade na empresa.",
 "Lens (lente: o papel de especialista que avalia aquela parte)": "Lens (lente): o ponto de vista de especialista usado para conferir uma etapa, como segurança, banco ou experiência do usuário.",
 "Links (ligações entre itens: bloqueia, é bloqueado por, tem relação com)": "Links (ligações): mostra quais itens dependem deste e de quais ele depende. Ajuda a ver o que trava o quê.",
 "Low (baixa)": "Low (prioridade baixa): pode esperar, entra quando sobrar tempo.",
 "Maintenance (percentual anual do valor do projeto, cobrado por mês)": "Maintenance (manutenção): uma mensalidade para manter o sistema funcionando e atualizado, calculada como uma porcentagem do valor do projeto por ano.",
 "Medium (média)": "Medium (prioridade média): entra no ritmo normal de trabalho.",
 "Mensalidades mais projetos pagos de uma vez, divididos pelos meses do projeto": "Receita por mês: as mensalidades somadas aos projetos pagos de uma vez, que são divididos pelos meses que o projeto dura.",
 "Migration (roteiro versionado de mudança na estrutura do banco)": "Migration (migração): um arquivo que registra cada mudança na estrutura do banco, em ordem. Permite refazer ou conferir tudo depois.",
 "Milestones (pagamento em parcelas, a cada entrega)": "Milestones (marcos): o pagamento é dividido em parcelas, e cada parcela é paga quando uma parte combinada é entregue.",
 "O comum em software house é de 15% a 30%": "Margem: quanto sobra de lucro depois de todos os custos e impostos. Em empresas de software, o comum é de 15% a 30%.",
 "On Hold (pausado)": "On Hold (pausado): o projeto parou por um tempo, por decisão, e volta depois.",
 "Overload (duas funções com o mesmo nome e parâmetros diferentes)": "Overload (função duplicada): duas funções no banco com o mesmo nome e entradas diferentes. O banco pode ficar sem saber qual usar e dar erro.",
 "Path (o caminho legível, como BL › YOU › Java Fiscal)": "Path (caminho): o endereço de um item em palavras, como BL › YOU › Java Fiscal. Mostra onde ele mora.",
 "Pass-through (repasse dos custos de terceiros, com uma taxa)": "Pass-through (repasse): o cliente paga os custos de serviços de terceiros usados no sistema dele, com uma pequena taxa por cima.",
 "Pass-through (repasse): o custo de terceiros cobrado do cliente, com a taxa definida": "Pass-through (repasse): o cliente paga os custos de serviços de terceiros usados no sistema dele, com a taxa definida por cima.",
 "Per user (valor por usuário ativo por mês)": "Per user (por usuário): o cliente paga por mês um valor para cada pessoa que usa o sistema.",
 "Percentual do valor do projeto cobrado por ano. O comum é de 15% a 20%": "Manutenção anual: a porcentagem do valor do projeto cobrada por ano para manter o sistema. O comum é de 15% a 20%.",
 "Planning (planejamento)": "Planning (planejamento): a etapa de dividir o trabalho em tarefas, estimar as horas e definir quem faz o quê e quando.",
 "Pode ser uma data antiga. O sistema soma tudo o que já foi cobrado desde essa data": "Início da cobrança: pode ser uma data antiga. O sistema soma tudo o que já foi cobrado desde esse dia até hoje.",
 "Pode ser uma data antiga. O sistema soma tudo o que já foi gasto desde essa data": "Início do custo: pode ser uma data antiga. O sistema soma tudo o que já foi gasto desde esse dia até hoje.",
 "Priority (prioridade)": "Priority (prioridade): o quanto este item é importante perto dos outros. Decide o que se faz primeiro.",
 "Product (produto)": "Product (produto): um grupo de aplicações de uma mesma empresa ou área, como todos os sistemas da YOU Contabilidade. É um nível opcional.",
 "Product (produto: um conjunto de aplicações de uma mesma unidade de negócio)": "Product (produto): um grupo de aplicações de uma mesma empresa ou área, como todos os sistemas da YOU Contabilidade. É um nível opcional.",
 "Production (o sistema em uso real pelos clientes)": "Production (produção): a versão do sistema que os clientes usam de verdade. Qualquer erro aqui afeta gente real.",
 "Project (projeto)": "Project (projeto): o trabalho contratado por um cliente, com começo, meio e fim. Dentro dele ficam os produtos e as aplicações.",
 "Provisão mensal de 1/12": "Provisão de 1/12: todo mês se guarda um doze avos do salário para pagar o 13º e as férias quando chegarem.",
 "Provisão mensal de 1/36": "Provisão de 1/36: todo mês se guarda uma parte para o terço de férias, que é pago junto com as férias.",
 "Provisão para a multa de 40% na demissão": "Multa do FGTS: uma reserva mensal para pagar a multa de 40% sobre o FGTS se a pessoa for demitida sem justa causa.",
 "QA & Security (testes e segurança)": "QA & Security (testes e segurança): a etapa de testar se tudo funciona e procurar brechas de segurança antes de entregar.",
 "Quick filters (filtros rápidos de um clique)": "Quick filters (filtros rápidos): botões que mostram só um tipo de item com um clique, como os seus ou os atrasados. Clique de novo para tirar.",
 "RLS (Row Level Security: regra no banco que decide quem vê cada linha)": "RLS (segurança por linha): uma regra dentro do banco que decide quem pode ver cada registro. Mesmo que a tela erre, o dado de outro cliente não aparece.",
 "RLS (regra no banco que decide quem vê cada linha)": "RLS (segurança por linha): uma regra dentro do banco que decide quem pode ver cada registro. Mesmo que a tela erre, o dado de outro cliente não aparece.",
 "Relationship (ligação fixa entre dois registros no banco)": "Relationship (ligação): uma conexão fixa entre dois registros, como a aplicação que pertence a um projeto. Não se perde se o nome mudar.",
 "Release (entrega no ar)": "Release (lançamento): a etapa de colocar a versão nova no ar, para os clientes usarem.",
 "Repositories (onde fica guardado o código)": "Repositories (repositórios): onde o código do sistema fica guardado, com o histórico de cada mudança, normalmente no GitHub.",
 "Reserva para imprevistos. O comum é de 10% a 20%": "Contingência: uma reserva no preço para cobrir o que der errado ou demorar mais. O comum é de 10% a 20%.",
 "Retainer (mensalidade fixa, com horas incluídas)": "Retainer (mensalidade fixa): o cliente paga todo mês um valor que já inclui um número de horas de trabalho.",
 "Retrospective (aprender com a entrega)": "Retrospective (retrospectiva): a conversa depois da entrega para ver o que deu certo, o que deu errado e o que mudar na próxima.",
 "Retrospective (retrospectiva: aprender com a entrega)": "Retrospective (retrospectiva): a conversa depois da entrega para ver o que deu certo, o que deu errado e o que mudar na próxima.",
 "Risco de acidente de trabalho": "RAT (risco de acidente de trabalho): um encargo sobre a folha que varia conforme o risco da atividade.",
 "Roles (papéis de acesso)": "Roles (papéis de acesso): o tipo de acesso de cada pessoa, como Master, Dev ou Stakeholder. Define o que cada uma pode ver e mudar.",
 "SLA (prazo combinado de resposta)": "SLA (prazo combinado): o tempo máximo que a IT.IA se compromete a levar para responder ou resolver um pedido.",
 "Schema (pasta de tabelas dentro do mesmo banco)": "Schema (pasta de tabelas): uma divisão dentro do banco para guardar as tabelas que só um projeto usa, sem misturar com as outras.",
 "Scoping (recorte do escopo)": "Scoping (escopo): a etapa de fechar o que entra e o que não entra no projeto, para não crescer sem controle.",
 "Secrets catalog (lista de segredos com nome e local, sem o valor)": "Secrets catalog (lista de segredos): a relação das senhas e chaves de acesso que o sistema usa, com o nome e onde ficam, mas nunca o valor.",
 "Secrets catalog (lista de segredos, sem os valores)": "Secrets catalog (lista de segredos): a relação das senhas e chaves de acesso que o sistema usa, com o nome e onde ficam, mas nunca o valor.",
 "Settings e Templates (configurações e modelos que valem para todo projeto novo)": "Settings e Templates (configurações e modelos): o padrão que todo projeto novo já recebe ao ser criado, como etapas e requisitos.",
 "Single database (um banco de dados só)": "Single database (banco único): todos os projetos da IT.IA ficam no mesmo banco, separados por código. Assim os painéis e a busca enxergam tudo junto.",
 "Sistema S e outras entidades": "Terceiros (Sistema S): encargos sobre a folha que vão para SESI, SENAI, SEBRAE e outras entidades.",
 "Skills (habilidades: o que a pessoa sabe fazer)": "Skills (habilidades): o que a pessoa sabe fazer, como banco de dados ou design. Ajuda a escolher quem pega cada tarefa.",
 "Soft delete (marcar como arquivado em vez de apagar de verdade)": "Soft delete (apagar sem perder): o registro é só marcado como arquivado e some das telas, mas continua guardado e pode voltar.",
 "Stack (conjunto de tecnologias usadas)": "Stack (tecnologias): as ferramentas e linguagens usadas para construir o sistema, como React, Java ou Supabase.",
 "Stage gates (etapas obrigatórias)": "Stage gates (etapas obrigatórias): os passos que todo projeto percorre. O sistema avisa se alguém tentar pular um passo sem entregar o que ele pede.",
 "Stakeholder (cliente que acompanha o projeto, sem executar)": "Stakeholder (interessado): a pessoa do cliente que acompanha o andamento, sem trabalhar nas tarefas. Vê só o que é dela.",
 "Start date (data de início)": "Start date (início): o dia em que o trabalho neste item começa. Junto com o prazo, define onde ele aparece na linha do tempo.",
 "Story (funcionalidade vista pelo usuário)": "Story (funcionalidade): uma coisa que o usuário vai conseguir fazer no sistema, como 'emitir segunda via do boleto'.",
 "Sub-task (subtarefa)": "Sub-task (subtarefa): um pedaço menor de uma tarefa, para dividir o trabalho em passos.",
 "Success fee (percentual do resultado, como faturamento ou recuperação)": "Success fee (taxa de sucesso): o cliente paga uma porcentagem do resultado que o sistema trouxe, como o valor recuperado.",
 "Swimlanes (faixas horizontais que agrupam o quadro)": "Swimlanes (faixas): divide o quadro em linhas, por responsável, prioridade ou frente, para ver cada grupo separado.",
 "System tag (etiqueta automática)": "System tag (etiqueta automática): criada pelo próprio sistema a partir das ligações, como a holding do cliente. Tem cadeado e ninguém apaga.",
 "System tags (etiquetas automáticas, geradas a partir das ligações)": "System tags (etiquetas automáticas): criadas pelo próprio sistema a partir das ligações, como a holding do cliente. Têm cadeado e ninguém apaga.",
 "Tag (etiqueta livre)": "Tag (etiqueta livre): uma palavra que você cola num item para achar e agrupar depois, como 'urgente' ou 'financeiro'.",
 "Tags (etiquetas)": "Tags (etiquetas): palavras coladas nos itens para achar e agrupar depois. Não mudam onde o item mora.",
 "Target date (data prevista de entrega)": "Target date (data prevista): quando se espera entregar. É uma previsão, diferente do prazo, que é o limite.",
 "Task (tarefa)": "Task (tarefa): uma ação concreta que uma pessoa faz, como 'criar a tela de login'.",
 "Tech sheet (ficha técnica)": "Tech sheet (ficha técnica): a página que reúne tudo o que é técnico do sistema, como tecnologias, banco, integrações e decisões.",
 "Tiered (planos em faixas, cada um com um limite)": "Tiered (planos por faixa): o preço muda conforme o tamanho do uso, como até 10 usuários, até 50, e assim por diante.",
 "Time and materials (cobra pelas horas trabalhadas)": "Time and materials (por hora): o cliente paga pelas horas que foram realmente trabalhadas.",
 "Time blocking (reservar um horário no calendário para trabalhar no item)": "Time blocking (reservar horário): marcar no calendário um bloco de tempo só para trabalhar neste item.",
 "Time blocking (reservar um horário para trabalhar numa tarefa)": "Time blocking (reservar horário): marcar no calendário um bloco de tempo só para trabalhar numa tarefa. Arraste para mudar o horário.",
 "To Do (a fazer)": "To Do (a fazer): o item já está planejado e pronto para alguém começar.",
 "UTC (o horário padrão mundial)": "UTC (horário mundial): o banco guarda as horas num padrão mundial e a tela converte para o horário de Brasília. Evita erro de fuso.",
 "Usage-based (cobra pelo que foi usado)": "Usage-based (por uso): o cliente paga conforme o que usou no mês, como mensagens enviadas ou notas emitidas.",
 "Value-based (preço pelo valor que o sistema gera para o cliente)": "Value-based (pelo valor gerado): o preço é definido pelo quanto o sistema faz o cliente ganhar ou economizar, e não pelas horas.",
 "Verification (verificação final)": "Verification (verificação): a etapa de conferir, com provas, que tudo o que foi pedido está funcionando antes da aprovação.",
 "Views (formas de ver o mesmo dado)": "Views (visões): jeitos diferentes de olhar os mesmos itens, como quadro, tabela ou calendário. Mudar numa muda em todas.",
 "Visibility (visibilidade: só interno ou visível ao cliente no painel dele)": "Visibility (visibilidade): decide se o cliente vê este item no painel dele ou se fica só para a equipe.",
 "Visual identity (identidade visual)": "Visual identity (identidade visual): as cores, letras e logotipo que o sistema do cliente deve usar.",
 "WIP limit (limite de cartões em andamento: a coluna fica vermelha se passar)": "WIP limit (limite em andamento): o máximo de itens que podem estar sendo feitos ao mesmo tempo. Se passar, a coluna fica vermelha, sinal de gente fazendo coisa demais junto.",
 "Waiver (dispensa registrada: não se aplica, com o motivo por escrito)": "Waiver (dispensa): quando uma exigência não faz sentido para este caso, ela é dispensada com o motivo escrito, para ficar registrado.",
 "Whiteboard (quadro visual livre)": "Whiteboard (quadro livre): um espaço para desenhar ideias, fluxos e rascunhos, como num quadro branco.",
 "Workstream (frente de trabalho onde o item fica)": "Workstream (frente de trabalho): a parte do sistema a que o item pertence, como Frontend, Backend ou Banco de dados.",
 "Workstream (frente de trabalho)": "Workstream (frente de trabalho): uma parte da aplicação, como Frontend, Backend ou Banco de dados. É o último nível da estrutura.",
 "Workstreams (frentes de trabalho) que toda aplicação deste serviço já recebe ao nascer": "Workstreams (frentes de trabalho): as partes que toda aplicação deste serviço já recebe ao ser criada, como Frontend e Backend.",
 "project_id (código do projeto a que a linha pertence)": "project_id (código do projeto): um campo em cada registro que diz a qual projeto ele pertence. É assim que o banco separa um projeto do outro.",
 "Capacity (capacidade: horas disponíveis por semana)": "Capacity (capacidade): quantas horas por semana a pessoa tem para trabalhar em tarefas. O sistema compara com a carga para ver quem está sobrando ou sobrecarregado.",
 "Severity (gravidade: sistema parado, função quebrada, incômodo ou cosmético)": "Severity (gravidade): o tamanho do problema, de sistema parado até um detalhe visual. Define a pressa da resposta.",
 "Stage gates (etapas com trava: só avança quando a etapa anterior entregou o que devia)": "Stage gates (etapas com trava): os passos que todo projeto percorre. Cada etapa pede uma entrega, e o sistema avisa se alguém tentar pular.",
 "Evals": "Evals (avaliações): testes que medem se o agente está respondendo certo.",
 "Focus (foco): em que você está trabalhando agora": "Focus (foco): marque a frente em que você está trabalhando agora, e o painel mostra só o que é dela.",
 'Advanced search (busca avançada no estilo JQL, a linguagem de busca do Jira): escreva campo = valor, e junte com " e "': 'Advanced search (busca avançada): escreva o campo e o valor que procura, como status = done, e junte mais de um com " e ". Também dá para digitar só uma palavra.',
 'Alíquota efetiva do Simples sobre o faturamento (varia pela faixa e pelo Fator R)': 'Alíquota do Simples: a porcentagem de imposto que a empresa paga sobre o que fatura no Simples Nacional. Muda conforme o faturamento e o peso da folha de pagamento.',
 'Parte do tempo que vira trabalho de cliente. O comum é de 50% a 70%': 'Horas faturáveis: a parte do tempo da equipe que vira trabalho cobrado de cliente, sem reuniões e tarefas internas. O comum é de 50% a 70%.',
 'Usado para custos em dólar. Quando o banco for ligado, atualiza sozinho': 'Câmbio: quanto vale um dólar em reais, usado para converter os custos em dólar. Quando o banco for ligado, atualiza sozinho todo dia.',
 'Contingency (contingência): reserva para imprevistos do projeto': 'Contingency (contingência): uma reserva no preço para cobrir o que der errado ou demorar mais do que o previsto.',
 'Deliverables (entregáveis): o que o cliente recebe no fim': 'Deliverables (entregáveis): a lista do que o cliente recebe no fim, como o sistema no ar, o manual e o acesso ao código.',
 'Tags (etiquetas livres: criadas, editadas e apagadas à vontade)': 'Tags (etiquetas livres): palavras que você cria, muda e apaga à vontade para agrupar clientes e projetos. Não mudam onde nada mora.',
 'Team (time): as pessoas, o que cada uma faz e quanto tempo tem': 'Team (time): as pessoas da equipe, o que cada uma faz e quantas horas tem por semana. É a base para planejar e calcular custo.',
 'Clients (clientes): quem contrata a IT.IA, de dentro ou de fora do grupo': 'Clients (clientes): as empresas que contratam a IT.IA, sejam do grupo Blanco & Lisboa ou de fora.',
 'Playbook (manual de regras da operação): o que vale para todo projeto, sempre.': 'Playbook (manual de regras): as regras que valem para todo projeto, sempre, do banco de dados às etapas obrigatórias.',
 'Tools (o que o agente pode fazer no sistema) e Permissions (até onde ele pode ir sozinho)': 'Tools e Permissions (ferramentas e permissões): o que o agente de IA consegue fazer no sistema e se ele pode fazer sozinho, se precisa pedir aprovação ou se é proibido.',
 'Logs (registro de tudo que o agente respondeu e fez) e Evals (testes que medem se ele está respondendo certo)': 'Logs e Evals (registro e avaliação): o histórico de tudo o que o agente respondeu e fez, e os testes que medem se ele está acertando.',
 'Playground (área de teste para conversar com o agente antes de soltar para os clientes)': 'Playground (área de teste): um lugar para conversar com o agente de IA e ver como ele responde, antes de liberar para os clientes.',
}
